name: Publicar site com AsciiDoc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Instalar Asciidoctor e converter AsciiDoc
        uses: asciidoctor/action-asciidoctor@v3
        with:
          source_dir: '.'
          output_dir: 'site-html'
      - name: Publicar no GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site-html'

deploy:
  needs: build
  runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
