name: Convert AsciiDoc to HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Asciidoctor
        run: sudo apt-get install asciidoctor

      - name: Convert .adoc to .html
        run: asciidoctor -D . index.adoc

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html
          git commit -m 'Convert .adoc to .html'
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Arthurfrc/arthurfrc.github.io.git
